#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 The Granite Authors
#
# Generate THIRD-PARTY-LICENSES.md from the module graph (LEG-006) and fail on
# any license that is not GPL-3.0-compatible (LEG-005).
#
#   ./scripts/gen-third-party-licenses.sh          regenerate the file
#   ./scripts/gen-third-party-licenses.sh --check  fail if stale or incompatible
#
# Output is deterministic: entries are sorted and no timestamp is embedded.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

out="THIRD-PARTY-LICENSES.md"
check=false
[[ "${1:-}" == "--check" ]] && check=true

gobin="$(go env GOPATH)/bin"
if [[ ! -x "$gobin/go-licenses" ]]; then
	echo "go-licenses not found in $gobin — run 'make tools'" >&2
	exit 1
fi

# Licenses that are compatible with GPL-3.0-or-later for a combined work.
# Keep this list conservative: an unlisted license is a review trigger, not a
# silent pass. See LEG-005.
allowed=(
	Apache-2.0 BSD-2-Clause BSD-3-Clause CC0-1.0 GPL-2.0-or-later
	GPL-3.0 GPL-3.0-only GPL-3.0-or-later ISC LGPL-2.1 LGPL-2.1-or-later
	LGPL-3.0 LGPL-3.0-or-later MIT MPL-2.0 Unlicense Zlib
)

csv="$(mktemp)"
trap 'rm -f "$csv"' EXIT

# go-licenses writes progress to stderr; only stdout is data.
"$gobin/go-licenses" csv ./... 2>/dev/null | LC_ALL=C sort > "$csv" || true

incompatible=()
while IFS=, read -r module url license; do
	[[ -z "${module:-}" ]] && continue
	# The module under audit is our own code, not a third-party component.
	[[ "$module" == github.com/CyberSecDef/granite* ]] && continue
	ok=false
	for a in "${allowed[@]}"; do
		[[ "$license" == "$a" ]] && ok=true && break
	done
	$ok || incompatible+=("$module ($license)")
done < "$csv"

tmp="$(mktemp)"
{
	cat <<'HEADER'
# Third-Party Licenses

Every third-party component linked into Granite, with its license. Granite is
distributed under GPL-3.0-or-later; every license listed here is compatible with
those terms (`LEG-005`). This file ships in every release artifact (`LEG-006`).

**Do not edit this file by hand.** Regenerate it with `make licenses` after
adding or removing a dependency.

HEADER

	if [[ ! -s "$csv" ]] || [[ -z "$(grep -v '^github.com/CyberSecDef/granite' "$csv" || true)" ]]; then
		cat <<'EMPTY'
## Components

_None._

Granite currently has no third-party dependencies. This is the desired steady
state for the core: prefer the standard library, and add a dependency only when
it earns its place (see CONTRIBUTING.md §5).
EMPTY
	else
		echo "## Components"
		echo
		echo "| Component | License | Source |"
		echo "|---|---|---|"
		while IFS=, read -r module url license; do
			[[ -z "${module:-}" ]] && continue
			[[ "$module" == github.com/CyberSecDef/granite* ]] && continue
			echo "| \`$module\` | $license | ${url:-—} |"
		done < "$csv"
	fi

	cat <<'FOOTER'

## Development-only tooling

Linters, generators, and test harnesses are not linked into any release
artifact and are therefore not listed above. They are declared in the `tools`
target of the Makefile.
FOOTER
} > "$tmp"

if [[ ${#incompatible[@]} -gt 0 ]]; then
	echo "✗ GPL-3.0-incompatible or unrecognized licenses found (LEG-005):" >&2
	printf '    %s\n' "${incompatible[@]}" >&2
	echo "  Remove the dependency, or add the license to the allowlist in $0 if it is genuinely compatible." >&2
	rm -f "$tmp"
	exit 1
fi

if $check; then
	if ! diff -q "$tmp" "$out" >/dev/null 2>&1; then
		echo "✗ $out is stale. Run 'make licenses' and commit the result." >&2
		diff -u "$out" "$tmp" >&2 || true
		rm -f "$tmp"
		exit 1
	fi
	rm -f "$tmp"
	echo "✓ $out is up to date; all licenses compatible"
else
	mv "$tmp" "$out"
	echo "✓ wrote $out"
fi
